version: '3.7'
services:
    mdm:
        build: .
        image: hwind/hmdm
        entrypoint: sleep
        command: 6h
        volumes: ['./content:/home/hmdmr']
        ports:
            - 8080:8080
        environment:
        - HMDM_SQL_BASE=hmdm
        - HMDM_SQL_USER=hmdm
        - HMDM_SQL_PASS=Q1XIpOTkWU9Z
        - PG_ROOT_PASSWORD=Q1XIpOTkWU9Z
        - PG_PORT=5432
        - PG_HOST=pgdb
    pgdb:
        hostname: 'pgdb'
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.5-0
        environment:
        - PGHOST=/tmp
        - MAX_CONNECTIONS=10
        - MAX_WAL_SENDERS=5
        - PG_MODE=primary
        - PG_PRIMARY_USER=primaryuser
        - PG_PRIMARY_PASSWORD=password
        - PG_DATABASE=hmdm
        - PG_USER=hmdm
        - PG_PASSWORD=Q1XIpOTkWU9Z
        - PG_ROOT_PASSWORD=Q1XIpOTkWU9Z
        - PG_PRIMARY_PORT=5432
        volumes:
        - ./pgdata:/pgdata
        ports:
        - "5432"